### PR TITLE
PHP 8.0 Support

### PR DESCRIPTION
**Pull request by Pezhvak**
- PHP 8.0
- Node 15.5.1
- NPM 7.3
- Composer 2 (Removed "hirak/prestissimo" since it's not needed anymore)
- GOSS 0.3.16

Note: I've removed xmlrpc for PHP 8.0 installations [read here](https://php.watch/versions/8.0/xmlrpc)

### CODE REVIEW

**Review by edbizarro — CHANGES_REQUESTED** [review]
The `.idea` dir must be in the .gitignore and not submitted

**Comment by Pezhvak** [comment]
@edbizarro done

**Comment by edbizarro** [comment]
> @edbizarro done

Thanks! I'll take a look

**Comment by briandotdev** [comment]
Darn I was also working a PR for this over the last two days 😂 

Did you run the Goss test with no errors?  AMQP extension in PECL is not yet PHP 8 compatible and in my testing was silently failing the entire [PECL install routine](https://github.com/edbizarro/gitlab-ci-pipeline-php/blob/916a5fc47db6661cd913a5f2681eaa69cbdab8e7/php/scripts/extensions.sh#L162-L164) for all other modules.  The container build didn't catch the error.

**Comment by Pezhvak** [comment]
> Darn I was also working a PR for this over the last two days 😂
> 
> Did you run the Goss test with no errors? AMQP extension in PECL is not yet PHP 8 compatible and in my testing was silently failing the entire [PECL install routine](https://github.com/edbizarro/gitlab-ci-pipeline-php/blob/916a5fc47db6661cd913a5f2681eaa69cbdab8e7/php/scripts/extensions.sh#L162-L164) for all other modules. The container build didn't catch the error.

please to check this PR and tell me if anything needs to be addressed. I'm already using built image from this in my CI/CD without any issue

**Comment by Pezhvak** [comment]
> Darn I was also working a PR for this over the last two days 😂
> 
> Did you run the Goss test with no errors? AMQP extension in PECL is not yet PHP 8 compatible and in my testing was silently failing the entire [PECL install routine](https://github.com/edbizarro/gitlab-ci-pipeline-php/blob/916a5fc47db6661cd913a5f2681eaa69cbdab8e7/php/scripts/extensions.sh#L162-L164) for all other modules. The container build didn't catch the error.

please do check and test this PR and tell me if anything needs to be addressed. I'm already using built image from it in my CI/CD without any issue.

**Comment by briandotdev** [comment]
> please do check and test this PR and tell me if anything needs to be addressed. I'm already using built image from it in my CI/CD without any issue.

Xdebug 2.9.0 is also not compatible with PHP 8.  Requires Xdebug 3.  That one was also silently failing.  What's the output of your Goss test after build?

**Comment by Pezhvak** [comment]
> > please do check and test this PR and tell me if anything needs to be addressed. I'm already using built image from it in my CI/CD without any issue.
> 
> Xdebug 2.9.0 is also not compatible with PHP 8. Requires Xdebug 3. That one was also silently failing. What's the output of your Goss test after build?

i will check those and get back to you, can't do it today

**Comment by briandotdev** [comment]
I'm showing the following tests failing on image built from this PR.
image

**Comment by Pezhvak** [comment]
@edbizarro it really means a lot for him, i close this PR in favor of #113.

**Comment by edbizarro** [comment]
c'mon guys

**Pull request closed without merging**
